#! /bin/sh
chosen=$(printf "Power Off\nRestart\nLock" | rofi -dmenu -i -theme-str '@import "power.rasi"')
case "$chosen" in
  "Power Off") systemctl poweroff ;;
  "Restart") systemctl reboot ;;
  "Lock") swaylock -f -c 000000 ;;
  *) exit 1 ;;
esac
